travis:
  secure:
    BINSTAR_TOKEN: BWU0ki5n/7UefDOeKo83Ul6crAMTQrMi7oyVoGHrLq0dqWqK4ru5T8QVNB0GAC1JfViH2YHU8FDPjWFngzVptU/qLP2Roi8ojb6hAAc46bXncht1zJiUt2cSmjPtg4gw44OtnKtOPV5lmzlNCKcM3kbOnvPSKLvVP3fxh7SLNvBHq5Zo9I0Vp5PUcrUnRPyoN6SPcdnF35vLSBQAaH4L7G89hL+554UEPvt7iQSWW6wRTY3DsWzjsMaUFNR8Usu58WYaJeDtWtlPAN2/5txv0U4SxeJfQVdxVCDkRATQSgfZohoUjzt4/MUYYLs8fjbfU7Np1f2BE9bRZbCeVLSwHg8jNy7dOGc++kLxhav7J829ao6Zf50R/6zJCZ9dIxcBTdPzLJHua2DSQFsa+EPdw6s6ihJAQgup3vMf69CiDPepVw/oMXUI5Z7YmHj3E9qYddy+07S++UhkqxpZ14+qvDZb2K9cp9SdY0GTSP6owAUUqKJjAtSH/oWsfGfvjQrQqqYKstO62Y0pHrReP3vkPy9u/Vg7Qec6KkFv7Bl9gVVnFjtjnm195fa5+LwX/X9OFhX8s1QAYzGdbp5HQWA5jGURzb2pgLla7RfH9SPi6H/ObbPWHN3RMabDYv9xgIUzIZH/W+eLOJTsyppH6p2M6eY61GD+fqpb8JJgpsTyDT8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
